// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAiwMKbChG0C0_j_Ilw12uvjdubuC7k0A',
    appId: '1:806896713005:web:598e0b54fd91bd8b19a7a4',
    messagingSenderId: '806896713005',
    projectId: 'barangaydev',
    authDomain: 'barangaydev.firebaseapp.com',
    storageBucket: 'barangaydev.appspot.com',
    measurementId: 'G-18G8EEZZ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LTlevg6ZSma8bkeYAaOB11JqBOP5cpM',
    appId: '1:806896713005:android:4b912fce9f72192c19a7a4',
    messagingSenderId: '806896713005',
    projectId: 'barangaydev',
    storageBucket: 'barangaydev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppj-MLZ2x__Ueao8USI63P6V-ylgduqY',
    appId: '1:806896713005:ios:db2ed01fca5fe2fd19a7a4',
    messagingSenderId: '806896713005',
    projectId: 'barangaydev',
    storageBucket: 'barangaydev.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBppj-MLZ2x__Ueao8USI63P6V-ylgduqY',
    appId: '1:806896713005:ios:db2ed01fca5fe2fd19a7a4',
    messagingSenderId: '806896713005',
    projectId: 'barangaydev',
    storageBucket: 'barangaydev.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAiwMKbChG0C0_j_Ilw12uvjdubuC7k0A',
    appId: '1:806896713005:web:52f49b8ed7a2538319a7a4',
    messagingSenderId: '806896713005',
    projectId: 'barangaydev',
    authDomain: 'barangaydev.firebaseapp.com',
    storageBucket: 'barangaydev.appspot.com',
    measurementId: 'G-SPRRLVKMCZ',
  );
}
